### ISSUE TITLE
Launch never finsihed

### ISSUE THREAD

**Issue by sunshine69** [osi-open-source/reporting-portal-agent-codeception#3]
Hi,

When I check the test item the dot is running forever until it times out by reportportal server even the test has been completed.

This has been reported in here https://github.com/reportportal/reportportal/issues/543

I tried to manually send some tests and reportportal works as expected, that is my launch is completed successfully.

Thus I conclude that it is not reportportal but the codeception integration caused the issues.

Please let me know if it is a known issue or I miss-configure somewhere - anything to fix it?

Thanks a lot

**Comment by osibg** [comment]
Hi,
We also experianced this a long time ago and couldn't find the exact issue. Most of the times it was working normally, but for some cases on failure or poor network it would not mark the tests as completed. We stopped using this module, but we want to at least support it, so we will add it to our task list and try to reproduce this issue soon. 

Thank you for your contribution.

**Comment by sunshine69** [comment]
I do not have that issues in my env so far. It might be not related to this stack but the codeception and the code, basically this stack only rely on codeception event and then hook up to it to create/update and finish launch. For some reason it might be that the event has not yet fired so the finish action never get executed thus causing the symtom.

Thus because it might not be this repo, I am closing it.
